# Generated by Django 5.0.7 on 2024-08-04 08:03

import paste.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('code', models.CharField(default=paste.models.generate_code, max_length=6, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiration_time', models.IntegerField(choices=[(5, '5 دقیقه'), (10, '10 دقیقه'), (30, '30 دقیقه'), (60, '1 ساعت'), (120, '2 ساعت'), (720, '12 ساعت'), (1440, '1 روز'), (10080, '7 روز'), (43200, '30 روز')])),
                ('is_active', models.BooleanField(default=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
