# Generated by Django 5.0.7 on 2024-08-04 11:04

import paste.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', validators=[paste.models.validate_file_size]),
        ),
    ]
