# Generated by Django 5.0.7 on 2024-08-06 14:08

import paste.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0002_paste_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='code',
            field=models.CharField(default=paste.models.generate_code, max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='paste',
            name='expiration_time',
            field=models.IntegerField(choices=[(5, '5 min'), (10, '10 min'), (30, '30 min'), (60, '1 hour'), (120, '2 hour'), (720, '12 hour'), (1440, '1 day'), (10080, '7 day'), (43200, '30 day')]),
        ),
    ]
