# Generated by Django 5.0.7 on 2024-08-06 16:33

import django_summernote.fields
import paste.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0003_alter_paste_code_alter_paste_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='content',
            field=django_summernote.fields.SummernoteTextField(),
        ),
        migrations.AlterField(
            model_name='paste',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', validators=[paste.validators.validate_file_size, paste.validators.validate_file_extension]),
        ),
    ]
